import streamlit as st 
st.title("HELLO , I'm Ishank Gera :sunglasses:")
st.header("I am currently pursuing BTech from Dronacharya college of Engineering , Gurugram")
st.subheader("Internships:")
st.text("Machine Learning Intern at Suvidha Foundation")
st.text("Full Stack developmwnt intern at innomatics reasearch labs")
st.text("Data Science intern at innomatics reasearch labs")
st.text("Technical Content Writer at GeeksforGeeks")
st.subheader(":orange[Educational background]")
st.text("BTech CSE(AI ML) - Dronacharya college of Engineering, Gurgram [2020-2024]")
st.text("Class XII - Jain Public School, Rewari")
st.text("Class X - Jain Public School, Rewari")
st.subheader(":red[Skills]")
st.text("Python Programming")
st.text("Data Structure and Algorithms")
st.text("C++")
st.snow()
